DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzIwMjUxMTE1LCJ1c2VySWQiOjJ9.30VXQfbCZCc-iCXTh4zrf9WfXG8zVnu49buRrZeOD0g